list: $/pensoft/eventreporting/models/eventsreportingattendants/columns.yaml
modelClass: Pensoft\EventReporting\Models\EventsreportingAttendants
title: EventsReportingAttendant
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'pensoft/eventreporting/eventsreportingattendant/update/:id'
